main: mc.mytestplugin.Main
name: MyTestPlugin
version: 1.0
author: domi
description: my test plugin
commands:
  testtest:
    description: An example command
    usage: /<command>
    aliases: [t]
    permission: myplugin.mycommand
    permission-message: You don't have permission.