main: mc.mytestplugin.MyTestPlugin
name: MyTestPlugin
version: 1.0
author: domi
description: my test plugin
commands:
  testtest:
    description: An example command
    usage: /<command>
    aliases: [t]
  runasplayer:
    description: 
    usage: /<command>
    aliases: [rap]
  fun:
    aliases: []
  suck:
    aliases: []